/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module encoder8to3(y, a);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  output [2:0] a;
  input [7:0] y;
  sky130_fd_sc_hd__nor2_1 _74_ (
    .A(_67_),
    .B(_66_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nor4_1 _75_ (
    .A(_67_),
    .B(_66_),
    .C(_69_),
    .D(_68_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__nor2_1 _76_ (
    .A(_73_),
    .B(_72_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__nand2_1 _77_ (
    .A(_73_),
    .B(_72_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__nor2_1 _78_ (
    .A(_70_),
    .B(_71_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__nand4b_1 _79_ (
    .A_N(_49_),
    .B(_50_),
    .C(_51_),
    .D(_48_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__nand2_1 _80_ (
    .A(_70_),
    .B(_71_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nand4b_1 _81_ (
    .A_N(_51_),
    .B(_53_),
    .C(_48_),
    .D(_49_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__nand2_1 _82_ (
    .A(_52_),
    .B(_54_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__nor4_1 _83_ (
    .A(_70_),
    .B(_71_),
    .C(_73_),
    .D(_72_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__xor2_1 _84_ (
    .A(_69_),
    .B(_68_),
    .X(_56_)
  );
  sky130_fd_sc_hd__nand3_1 _85_ (
    .A(_47_),
    .B(_55_),
    .C(_56_),
    .Y(_57_)
  );
  sky130_fd_sc_hd__nand2_1 _86_ (
    .A(_52_),
    .B(_57_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__nor4b_1 _87_ (
    .A(_70_),
    .B(_71_),
    .C(_72_),
    .D_N(_73_),
    .Y(_58_)
  );
  sky130_fd_sc_hd__nor4b_1 _88_ (
    .A(_70_),
    .B(_73_),
    .C(_72_),
    .D_N(_71_),
    .Y(_59_)
  );
  sky130_fd_sc_hd__o21ai_0 _89_ (
    .A1(_58_),
    .A2(_59_),
    .B1(_48_),
    .Y(_60_)
  );
  sky130_fd_sc_hd__nor4b_1 _90_ (
    .A(_66_),
    .B(_69_),
    .C(_68_),
    .D_N(_67_),
    .Y(_61_)
  );
  sky130_fd_sc_hd__nor4b_1 _91_ (
    .A(_67_),
    .B(_66_),
    .C(_68_),
    .D_N(_69_),
    .Y(_62_)
  );
  sky130_fd_sc_hd__o21ai_0 _92_ (
    .A1(_61_),
    .A2(_62_),
    .B1(_55_),
    .Y(_63_)
  );
  sky130_fd_sc_hd__nand2_1 _93_ (
    .A(_60_),
    .B(_63_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__nor4b_1 _94_ (
    .A(_67_),
    .B(_69_),
    .C(_68_),
    .D_N(_66_),
    .Y(_64_)
  );
  sky130_fd_sc_hd__o21ai_0 _95_ (
    .A1(_61_),
    .A2(_64_),
    .B1(_55_),
    .Y(_65_)
  );
  sky130_fd_sc_hd__nand4_1 _96_ (
    .A(_52_),
    .B(_54_),
    .C(_57_),
    .D(_65_),
    .Y(_46_)
  );
  \$_DLATCH_P_  _97_ (
    .D(_00_[0]),
    .E(_01_),
    .Q(a[0])
  );
  \$_DLATCH_P_  _98_ (
    .D(_00_[1]),
    .E(_01_),
    .Q(a[1])
  );
  \$_DLATCH_P_  _99_ (
    .D(_00_[2]),
    .E(_01_),
    .Q(a[2])
  );
  assign _67_ = y[1];
  assign _66_ = y[0];
  assign _69_ = y[3];
  assign _68_ = y[2];
  assign _70_ = y[4];
  assign _71_ = y[5];
  assign _73_ = y[7];
  assign _72_ = y[6];
  assign _00_[2] = _45_;
  assign _00_[1] = _44_;
  assign _00_[0] = _43_;
  assign _01_ = _46_;
endmodule
