/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module dff(D, clk, rstn, Q, Qb);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input D;
  output Q;
  output Qb;
  input clk;
  input rstn;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(_3_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_0_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(D),
    .Q(Q),
    .RESET_B(_4_)
  );
  assign _3_ = rstn;
  assign _4_ = _2_;
  assign _0_ = Q;
  assign Qb = _1_;
endmodule
